name: 'Immutaverse Firmware Signing'
description: 'Send changed .bin files to the Immutaverse signing API'
author: 'Immutaverse Inc.'

inputs:
  imt-token:
    description: 'GitHub token for checkout and API auth'
    required: true
  sign-key:
    description: 'Immutaverse signing key'
    required: true

branding:
  icon: 'lock'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.imt-token }}

    - name: Get changed files
      id: changes
      shell: bash
      run: |
        git fetch --depth=2
        files=$(git diff --name-only HEAD^ HEAD)
        echo "files<<EOF" >> $GITHUB_OUTPUT
        echo "$files" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Send files for signing
      shell: bash
      env:
        TOKEN: ${{ inputs.imt-token }}
        KEY: ${{ inputs.sign-key }}
        REPO: ${{ github.repository }}
        BRANCH: ${{ github.ref_name }}
        REF: ${{ github.ref }}
        COMMIT: ${{ github.sha }}
        ACTION_VERSION: ${{ github.action_ref }}
        # ACTION_VERSION: "0.0.0" 
      run: |
        for file in "${{ steps.changes.outputs.files }}"; do
          echo "DEBUG REPO=$REPO"
          echo "DEBUG BRANCH=$BRANCH"
          echo "DEBUG REF=$REF"
          echo "DEBUG COMMIT_ID=$COMMIT"
          payload="{\"repo\":\"$REPO\",\"branch\":\"$BRANCH\",\"commit\":\"$COMMIT\",\"file\":\"$file\",\"key\":\"$KEY\",\"action_version\":\"$ACTION_VERSION\"}"
          echo "DEBUG PAYLOAD $payload"
          response=$(curl -s -w "\n%{http_code}" \
            -X POST "https://app.immutaverse.com/actions/signRequest.php" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d "$payload")
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          echo "File: $file → Status: $http_code"
          echo "Response: $body"
          if [ "$http_code" != "200" ]; then
            error_msg=$(echo "$body" | jq -r '.message // "API failed"')
            error_code=$(echo "$body" | jq -r '.error_code // empty')
            if [ "$error_code" = "VERSION_MISMATCH" ]; then
              echo "::error::Action version mismatch. Please update your workflow to the latest version."
            elif [ "$error_code" = "SUBSCRIPTION_INACTIVE" ]; then
              echo "::error::Your Immutaverse subscription is not active."
            else
              echo "::error::$error_msg"
            fi
            exit 1
          fi
        done
